plugins {
    id 'java'
    id 'org.jetbrains.kotlin.jvm' version '2.4.10'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

kotlin {
    jvmToolchain(17)
}

sourceSets {
    main {
        java.srcDirs = ['src']
        kotlin.srcDirs = ['src']
    }
    test {
        java.srcDirs = ['test']
        kotlin.srcDirs = ['test']
    }
}

repositories {
    mavenLocal()
    mavenCentral()
    maven { url = "https://maven.xpdustry.com/mindustry" }
    maven { url = "https://raw.githubusercontent.com/Zelaux/MindustryRepo/master/repository" }
    maven { url = 'https://www.jitpack.io' }
}

ext {
    mindustryVersion = 'v159.7'
}

dependencies {
    implementation "com.github.Anuken.Arc:arc-core:$mindustryVersion"
    implementation "com.github.Anuken.Mindustry:core:$mindustryVersion"

    testImplementation(platform('org.junit:junit-bom:5.10.1'))
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.1'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}

// 强制 Arc 版本统一
configurations.configureEach {
    resolutionStrategy.eachDependency { details ->
        if (details.requested.group == 'com.github.Anuken.Arc') {
            details.useVersion "$mindustryVersion"
        }
    }
}

tasks.register('run', JavaExec) {
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'mlogix.Main'
    args 'c'
    ignoreExitValue = true as JavaExecSpec
    errorOutput = System.err
    doLast {
        if (executionResult.get().exitValue != 0) {
            println "程序执行失败，退出码: ${executionResult.get().exitValue}"
        }
    }
}

tasks.register('run-debug', JavaExec) {
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'mlogix.Main'
    args 'c', 'd'
    ignoreExitValue = true as JavaExecSpec
    errorOutput = System.err
    doLast {
        if (executionResult.get().exitValue != 0) {
            println "程序执行失败，退出码: ${executionResult.get().exitValue}"
        }
    }
}
